production_job:
    stage: deploy
    only: 
      - develop2
      
    before_script:
        # Generate SSH Key
        - mkdir -p ~/.ssh
        - echo "$PROD_SSH_PRIVATE" | tr -d '\r' > ~/.ssh/id_rsa
        - chmod 600 ~/.ssh/id_rsa
        - '[[ -f /.dockerenv ]] && echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config'
        
    script:
      - bash .deploy-production.sh
      
    environment:
      name: production
      url: http://graphs2.analysed.ai/
